[project]
name = "paper-to-notion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "customtkinter>=5.2.2",
    "feedparser>=6.0.12",
    "ipykernel>=6.30.1",
    "pydantic>=2.11.9",
    "requests>=2.32.5",
]
